version: '3.4'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: dev
    volumes:
      - './frontend/src:/app'
    ports:
      - '8080:8080'
    environment:
      VUE_APP_API_ENDPOINT: http://localhost:8081
  basket:
    build:
      context: .
      dockerfile: basket/Dockerfile
      target: dev
    volumes:
      - './basket/src:/app'
    depends_on:
      - basket-cache
      - event-bus
    environment:
      CACHE_HOST: basket-cache
      CACHE_PORT: 6379
      EVENT_BUS_URL: amqp://event-bus
  basket-cache:
    image: redis:alpine
  catalog:
    build:
      context: .
      dockerfile: catalog/Dockerfile
      target: dev
    volumes:
      - './catalog/src:/app'
    depends_on:
      - catalog-db
      - event-bus
    environment:
      DB_URL: mongodb://catalog-db:27017/catalog
      EVENT_BUS_URL: amqp://event-bus
  catalog-db:
    image: mongo
    volumes:
      - '/data/db'
  event-bus:
    image: rabbitmq
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
      target: dev
    ports:
      - '8081:80'
    volumes:
      - './gateway/src:/app'
